In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
dataset = pd.read_csv("DATA2.csv")

In [3]:
df = pd.DataFrame(dataset)

In [4]:
df

       Name   Age  Marks Performance
0     Rohan  18.0   60.0          No
1  Spoorthi  22.0   70.0         Yes
2       Ram  21.0   67.0          No
3    Sachin  20.0   76.0          No
4     Madhu  26.0    NaN         Yes
5       Sam  23.0   58.0         Yes
6       Anu   NaN   80.0          No
7  Bharathi  24.0   90.0         Yes
8     Sammu  25.0    NaN          No
9      Asha  28.0   82.0         Yes

In [5]:
df.isnull().sum()

Name           0
Age            1
Marks          2
Performance    0
dtype: int64

In [6]:
df2 = df.copy()

In [7]:
mean_salary = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_salary)
avg_age = df['Marks'].mean()
df['Marks'] = df['Marks'].fillna(avg_age)
df

       Name   Age   Marks Performance
0     Rohan  18.0  60.000          No
1  Spoorthi  22.0  70.000         Yes
2       Ram  21.0  67.000          No
3    Sachin  20.0  76.000          No
4     Madhu  26.0  72.875         Yes
5       Sam  23.0  58.000         Yes
6       Anu  23.0  80.000          No
7  Bharathi  24.0  90.000         Yes
8     Sammu  25.0  72.875          No
9      Asha  28.0  82.000         Yes

In [8]:
df.isnull().sum()

Name           0
Age            0
Marks          0
Performance    0
dtype: int64

In [9]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [10]:
print(X)

[['Rohan' 18.0 60.0]
 ['Spoorthi' 22.0 70.0]
 ['Ram' 21.0 67.0]
 ['Sachin' 20.0 76.0]
 ['Madhu' 26.0 72.875]
 ['Sam' 23.0 58.0]
 ['Anu' 23.0 80.0]
 ['Bharathi' 24.0 90.0]
 ['Sammu' 25.0 72.875]
 ['Asha' 28.0 82.0]]

In [11]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']

In [12]:
df.isnull().sum()

Name           0
Age            0
Marks          0
Performance    0
dtype: int64

In [13]:
df1 = df.copy()

In [14]:
# FIRST MENTHOD: DROPNA

# summarize the shape of the raw data
print("Before:",df1.shape)

# drop rows with missing values
df1.dropna(inplace=True)

# summarize the shape of the data with missing rows removed
print("After:",df1.shape)

Before: (10, 4)
After: (10, 4)

In [15]:
# 5- Encoding the categorical data
# Solution 1 : ColumnTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [16]:
df

       Name   Age   Marks Performance
0     Rohan  18.0  60.000          No
1  Spoorthi  22.0  70.000         Yes
2       Ram  21.0  67.000          No
3    Sachin  20.0  76.000          No
4     Madhu  26.0  72.875         Yes
5       Sam  23.0  58.000         Yes
6       Anu  23.0  80.000          No
7  Bharathi  24.0  90.000         Yes
8     Sammu  25.0  72.875          No
9      Asha  28.0  82.000         Yes

In [17]:
print(X)

  (0, 5)	1.0
  (0, 10)	18.0
  (0, 11)	60.0
  (1, 9)	1.0
  (1, 10)	22.0
  (1, 11)	70.0
  (2, 4)	1.0
  (2, 10)	21.0
  (2, 11)	67.0
  (3, 6)	1.0
  (3, 10)	20.0
  (3, 11)	76.0
  (4, 3)	1.0
  (4, 10)	26.0
  (4, 11)	72.875
  (5, 7)	1.0
  (5, 10)	23.0
  (5, 11)	58.0
  (6, 0)	1.0
  (6, 10)	23.0
  (6, 11)	80.0
  (7, 2)	1.0
  (7, 10)	24.0
  (7, 11)	90.0
  (8, 8)	1.0
  (8, 10)	25.0
  (8, 11)	72.875
  (9, 1)	1.0
  (9, 10)	28.0
  (9, 11)	82.0

In [18]:
df2=df.copy()
df2

       Name   Age   Marks Performance
0     Rohan  18.0  60.000          No
1  Spoorthi  22.0  70.000         Yes
2       Ram  21.0  67.000          No
3    Sachin  20.0  76.000          No
4     Madhu  26.0  72.875         Yes
5       Sam  23.0  58.000         Yes
6       Anu  23.0  80.000          No
7  Bharathi  24.0  90.000         Yes
8     Sammu  25.0  72.875          No
9      Asha  28.0  82.000         Yes

In [19]:
pd.get_dummies(df2)

,Age,Marks,Name_Anu,Name_Asha,Name_Bharathi,Name_Madhu,Name_Ram,Name_Rohan,Name_Sachin,Name_Sam,Name_Sammu,Name_Spoorthi,Performance_No,Performance_Yes
0,18.0,60.000,False,False,False,False,False,True,False,False,False,False,True,False
1,22.0,70.000,False,False,False,False,False,False,False,False,False,True,False,True
2,21.0,67.000,False,False,False,False,True,False,False,False,False,False,True,False
3,20.0,76.000,False,False,False,False,False,False,True,False,False,False,True,False
4,26.0,72.875,False,False,False,True,False,False,False,False,False,False,False,True
5,23.0,58.000,False,False,False,False,False,False,False,True,False,False,False,True
6,23.0,80.000,True,False,False,False,False,False,False,False,False,False,True,False
7,24.0,90.000,False,False,True,False,False,False,False,False,False,False,False,True
8,25.0,72.875,False,False,False,False,False,False,False,False,True,False,True,False
9,28.0,82.000,False,True,False,False,False,False,False,False,False,False,False,True

In [20]:
print(X)

  (0, 5)	1.0
  (0, 10)	18.0
  (0, 11)	60.0
  (1, 9)	1.0
  (1, 10)	22.0
  (1, 11)	70.0
  (2, 4)	1.0
  (2, 10)	21.0
  (2, 11)	67.0
  (3, 6)	1.0
  (3, 10)	20.0
  (3, 11)	76.0
  (4, 3)	1.0
  (4, 10)	26.0
  (4, 11)	72.875
  (5, 7)	1.0
  (5, 10)	23.0
  (5, 11)	58.0
  (6, 0)	1.0
  (6, 10)	23.0
  (6, 11)	80.0
  (7, 2)	1.0
  (7, 10)	24.0
  (7, 11)	90.0
  (8, 8)	1.0
  (8, 10)	25.0
  (8, 11)	72.875
  (9, 1)	1.0
  (9, 10)	28.0
  (9, 11)	82.0

In [21]:
df2=df.copy()
df2

       Name   Age   Marks Performance
0     Rohan  18.0  60.000          No
1  Spoorthi  22.0  70.000         Yes
2       Ram  21.0  67.000          No
3    Sachin  20.0  76.000          No
4     Madhu  26.0  72.875         Yes
5       Sam  23.0  58.000         Yes
6       Anu  23.0  80.000          No
7  Bharathi  24.0  90.000         Yes
8     Sammu  25.0  72.875          No
9      Asha  28.0  82.000         Yes

In [22]:
pd.get_dummies(df2)

,Age,Marks,Name_Anu,Name_Asha,Name_Bharathi,Name_Madhu,Name_Ram,Name_Rohan,Name_Sachin,Name_Sam,Name_Sammu,Name_Spoorthi,Performance_No,Performance_Yes
0,18.0,60.000,False,False,False,False,False,True,False,False,False,False,True,False
1,22.0,70.000,False,False,False,False,False,False,False,False,False,True,False,True
2,21.0,67.000,False,False,False,False,True,False,False,False,False,False,True,False
3,20.0,76.000,False,False,False,False,False,False,True,False,False,False,True,False
4,26.0,72.875,False,False,False,True,False,False,False,False,False,False,False,True
5,23.0,58.000,False,False,False,False,False,False,False,True,False,False,False,True
6,23.0,80.000,True,False,False,False,False,False,False,False,False,False,True,False
7,24.0,90.000,False,False,True,False,False,False,False,False,False,False,False,True
8,25.0,72.875,False,False,False,False,False,False,False,False,True,False,True,False
9,28.0,82.000,False,True,False,False,False,False,False,False,False,False,False,True

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [24]:
print(y)

[0 1 0 0 1 1 0 1 0 1]

In [25]:
X

array(<10x12 sparse matrix of type '<class 'numpy.float64'>'
	with 30 stored elements in Compressed Sparse Row format>, dtype=object)