In [156]:
# Data Prerpocessing Program 
print('Hola')

Hola

In [157]:
#Importing the Libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing  import LabelEncoder , MinMaxScaler
from sklearn.model_selection import train_test_split

In [158]:
#Step 2 Load The Datasaet
#df = pd.read_excel(Book001.xlsx)
dataset = pd.read_excel("Book001.xlsx")

In [159]:
df = pd.DataFrame(dataset)

In [160]:
dataset

           Name  Age  Gender         City  Marks
0         Gopal   19    Male    Bengaluru     33
1          Noah   45    Male       Winden     96
2       Nielsen   16    Male       Winden     46
3        Ulrich   40    Male       Winden     42
4    Charolette   39  Female      Winden      68
5        Hannah   42  Female      Hawkins     38
6       Claudia   87  Female        Renol     78
7   TiedaMaleen   94    Male        Nelod     95
8         Jonas   27    Male       Winden     67
9     Cathorina   43  Female       German     54
10    Elizabeth   29  Female       Winden     38
11       Martha   26  Female       German     45
12        Angel   17  Female  Pensylvania     32
13        Shibu   20    Male    Sajan rao     96

In [161]:
print(dataset)

           Name  Age  Gender         City  Marks
0         Gopal   19    Male    Bengaluru     33
1          Noah   45    Male       Winden     96
2       Nielsen   16    Male       Winden     46
3        Ulrich   40    Male       Winden     42
4    Charolette   39  Female      Winden      68
5        Hannah   42  Female      Hawkins     38
6       Claudia   87  Female        Renol     78
7   TiedaMaleen   94    Male        Nelod     95
8         Jonas   27    Male       Winden     67
9     Cathorina   43  Female       German     54
10    Elizabeth   29  Female       Winden     38
11       Martha   26  Female       German     45
12        Angel   17  Female  Pensylvania     32
13        Shibu   20    Male    Sajan rao     96

In [162]:
df.isnull().sum()

Name      0
Age       0
Gender    0
City      0
Marks     0
dtype: int64

In [163]:
x = df.iloc[:,:-1].values
y = df.iloc[:,:-1].values

In [164]:
print(x)

[['Gopal' 19 'Male' 'Bengaluru']
 ['Noah' 45 'Male' 'Winden']
 ['Nielsen' 16 'Male' 'Winden']
 ['Ulrich' 40 'Male' 'Winden']
 ['Charolette' 39 'Female' 'Winden ']
 ['Hannah' 42 'Female' 'Hawkins']
 ['Claudia' 87 'Female' 'Renol']
 ['TiedaMaleen' 94 'Male' 'Nelod']
 ['Jonas' 27 'Male' 'Winden']
 ['Cathorina' 43 'Female' 'German']
 ['Elizabeth' 29 'Female' 'Winden']
 ['Martha' 26 'Female' 'German']
 ['Angel' 17 'Female' 'Pensylvania']
 ['Shibu' 20 'Male' 'Sajan rao']]

In [165]:
df2=df.copy()

In [166]:
mean_salary = df["Age"].mean()
df['Age'] = df['Age'].fillna(mean_salary)
avg_age = df['Marks'].mean()
df['Marks'] = df['Marks'].fillna(avg_age)
df

           Name  Age  Gender         City  Marks
0         Gopal   19    Male    Bengaluru     33
1          Noah   45    Male       Winden     96
2       Nielsen   16    Male       Winden     46
3        Ulrich   40    Male       Winden     42
4    Charolette   39  Female      Winden      68
5        Hannah   42  Female      Hawkins     38
6       Claudia   87  Female        Renol     78
7   TiedaMaleen   94    Male        Nelod     95
8         Jonas   27    Male       Winden     67
9     Cathorina   43  Female       German     54
10    Elizabeth   29  Female       Winden     38
11       Martha   26  Female       German     45
12        Angel   17  Female  Pensylvania     32
13        Shibu   20    Male    Sajan rao     96

In [167]:
df_row_deleted = df.dropna()

print("\n After the Row Deletion")
df_row_deleted

 After the Row Deletion

           Name  Age  Gender         City  Marks
0         Gopal   19    Male    Bengaluru     33
1          Noah   45    Male       Winden     96
2       Nielsen   16    Male       Winden     46
3        Ulrich   40    Male       Winden     42
4    Charolette   39  Female      Winden      68
5        Hannah   42  Female      Hawkins     38
6       Claudia   87  Female        Renol     78
7   TiedaMaleen   94    Male        Nelod     95
8         Jonas   27    Male       Winden     67
9     Cathorina   43  Female       German     54
10    Elizabeth   29  Female       Winden     38
11       Martha   26  Female       German     45
12        Angel   17  Female  Pensylvania     32
13        Shibu   20    Male    Sajan rao     96

In [169]:
print('Hola Vecna')

Hola Vecna